1. Vector
2. Factor
3. List 
4. Matrix
5. Array
6. Data Frame

# I. Type_class

## 1. Vector

In [1]:
pass <- TRUE
# pass = true # Error

In [2]:
print(class(pass))

[1] "logical"


In [3]:
a <- 12.3 
b <- 150
print(class(a))

[1] "numeric"


In [4]:
int <- -2L # Defaul 32, L = 64
print(class(int))
print(int)# Ghi chú nè

[1] "integer"
[1] -2


In [5]:
ky_tu <- 'a'
print(class(ky_tu))

[1] "character"


In [6]:
fruit <- c("apple","pear","orange","banana")
fruit_ <- c("apple","pear","orange","banana",TRUE,1212)
fruit_3 <- c(12,24,4,4,5,5,5,TRUE,1212)
# Vector
print(class(fruit))
print(class(fruit_))
print(class(fruit_3)) # The class is the most type of element

[1] "character"
[1] "character"
[1] "numeric"


## 2. Factor

In [7]:
apple_color <- c('green', 'green', 'yellow', 'red', 'red')
factor_apple <- factor(apple_color)

print(factor_apple)
print(nlevels(factor_apple))

[1] green  green  yellow red    red   
Levels: green red yellow
[1] 3


## 3. List

In [8]:
list1 <- list(c(2,5,3), 21.3, "spring")
print(list1) # Index R begining at 1

[[1]]
[1] 2 5 3

[[2]]
[1] 21.3

[[3]]
[1] "spring"



## 4. Matrix

In [9]:
M <- matrix(c(1,2,3,4,5,6,7,8,9), nrow=2, ncol=4, byrow=TRUE)
print(M)

Warning message in matrix(c(1, 2, 3, 4, 5, 6, 7, 8, 9), nrow = 2, ncol = 4, byrow = TRUE):
"data length [9] is not a sub-multiple or multiple of the number of rows [2]"


     [,1] [,2] [,3] [,4]
[1,]    1    2    3    4
[2,]    5    6    7    8


In [10]:
M <- matrix(c(1,2,3,4,5,6,7,8), nrow=2, ncol=4, byrow=TRUE)
print(M)

     [,1] [,2] [,3] [,4]
[1,]    1    2    3    4
[2,]    5    6    7    8


In [11]:
M_ <- matrix(c(1,2,3,4,5,6,7,8,9), nrow=3, byrow=TRUE)
print(M_)

     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6
[3,]    7    8    9


In [12]:
print(M_[1,1])
print(M_[1,2])
print(M_[3,2])

[1] 1
[1] 2
[1] 8


## 5. Array - 

In [13]:
a <- array(c('red','green','yellow'), dim=c(3,3,2))

In [14]:
print(a)

, , 1

     [,1]     [,2]     [,3]    
[1,] "red"    "red"    "red"   
[2,] "green"  "green"  "green" 
[3,] "yellow" "yellow" "yellow"

, , 2

     [,1]     [,2]     [,3]    
[1,] "red"    "red"    "red"   
[2,] "green"  "green"  "green" 
[3,] "yellow" "yellow" "yellow"



## 6. DataFrame

In [15]:
BMI <- data.frame(gender = c("Male","Female","Male"),
                 height = c(152,171.5,165),
                 weight = c(81,93,78),
                 age = c(42,38,26))

In [16]:
print(BMI)

  gender height weight age
1   Male  152.0     81  42
2 Female  171.5     93  38
3   Male  165.0     78  26


# II. Variable

In [17]:
colors <- c('red','green','blue')
print(colors)

[1] "red"   "green" "blue" 


In [18]:
numbers <- c(10,15.5 ,7)
print(numbers)

[1] 10.0 15.5  7.0


In [19]:
c(TRUE, FALSE, TRUE, TRUE) -> pass 
print(pass)

[1]  TRUE FALSE  TRUE  TRUE


In [20]:
# help(print) Documentation R
# example(print)

In [21]:
print(ls())

 [1] "a"            "apple_color"  "b"            "BMI"          "colors"      
 [6] "factor_apple" "fruit"        "fruit_"       "fruit_3"      "int"         
[11] "ky_tu"        "list1"        "M"            "M_"           "numbers"     
[16] "pass"        


# III. Operators

1. Arthmetic Operators

In [22]:
v <- c(2, 5.5, 6)
t <- c(8,3,4)
print(v+t)

[1] 10.0  8.5 10.0


In [23]:
print(v-t)

[1] -6.0  2.5  2.0


In [24]:
print(v*t)

[1] 16.0 16.5 24.0


In [25]:
print(v/t)

[1] 0.250000 1.833333 1.500000


In [26]:
print(v%%t)

[1] 2.0 2.5 2.0


In [27]:
# print(v%t) # Error

In [28]:
print(v%/%t)

[1] 0 1 1


In [29]:
print(v^t)

[1]  256.000  166.375 1296.000


2 . Relational Operators

In [30]:
print(v>t)

[1] FALSE  TRUE  TRUE


In [31]:
print(v==t)

[1] FALSE FALSE FALSE


In [32]:
print(v>=t)

[1] FALSE  TRUE  TRUE


In [33]:
print(v!=t)

[1] TRUE TRUE TRUE


3. Logical Operators

In [34]:
v <- c(3,1,TRUE,0)
t <- c(4,1,FALSE,2)

In [35]:
print(v&t)

[1]  TRUE  TRUE FALSE FALSE


In [36]:
print(v|t)

[1] TRUE TRUE TRUE TRUE


In [37]:
print(!v)

[1] FALSE FALSE FALSE  TRUE


In [38]:
print(!t)

[1] FALSE FALSE  TRUE FALSE


In [39]:
# Just compare only couple first 

In [40]:
v <- c(FALSE, 1, TRUE, 0)
t <- c(4,1,FALSE,2)

print(v&&t)
print(v||t)

[1] FALSE
[1] TRUE


In [41]:
v1 <<- c(3,1, TRUE)
print(v1)

[1] 3 1 1


In [42]:
c(3,1,TRUE) ->> v2
print(v2)

[1] 3 1 1


In [43]:
v <- 1:10
print(v)

 [1]  1  2  3  4  5  6  7  8  9 10


In [44]:
v1 <- 8 
v2 <- 12
print(v1 %in% v)
print(v2 %in% v)

[1] TRUE
[1] FALSE


In [45]:
M = matrix(c(1,1,1,2,2,2), nrow=2, ncol=3, byrow=TRUE)
print(M)

     [,1] [,2] [,3]
[1,]    1    1    1
[2,]    2    2    2


In [46]:
t = M * M 
print(t)

     [,1] [,2] [,3]
[1,]    1    1    1
[2,]    4    4    4


In [47]:
print(t(M)) # Transpose Matrix M

     [,1] [,2]
[1,]    1    2
[2,]    1    2
[3,]    1    2


In [48]:
print(M %*% t(M)) # Multiple matrix

     [,1] [,2]
[1,]    3    6
[2,]    6   12


# IV. Import & Export

In [49]:
name <- readline(prompt='Enter name: ')

Enter name: Hai Anh


In [50]:
# age <- readline(prompt='Enter age: ')

In [51]:
age <- as.integer(readline(prompt='Enter age: '))
print(age)

Enter age: 232.42342
[1] 232


In [52]:
print(paste("Hi ",name, "next year you will be",age+1,"year old."))

[1] "Hi  Hai Anh next year you will be 233 year old."


In [53]:
colors <- c('red','green','blue')
colors

[1] "red"   "green" "blue"

In [54]:
cat("colors are",colors,"\nThe end")

colors are red green blue 
The end

# V. String

In [55]:
s1 <- "This is a first sentence."
s2 <- "This is a second sentence."
s3 <- "This is a 'third' sentence."
s4 <- 'This is a "fourth" sentence.'

In [56]:
print(s1)
print(s2)
print(s3)
print(s4)

[1] "This is a first sentence."
[1] "This is a second sentence."
[1] "This is a 'third' sentence."
[1] "This is a \"fourth\" sentence."


In [57]:
a <- 'one'
b <- 'two'
c <- 'three'

In [58]:
print(paste(a,b,c))
print(paste(a,b,c,sep=""))
print(paste(a,b,c,sep="-"))

[1] "one two three"
[1] "onetwothree"
[1] "one-two-three"


In [59]:
# d = cat(a,b,c)
d = paste(a,b,c)
print(d)

[1] "one two three"


In [60]:
s <- "This is a string"

In [61]:
print(nchar(s))

[1] 16


In [62]:
print(toupper(s))

[1] "THIS IS A STRING"


In [63]:
print(tolower(s))

[1] "this is a string"


In [64]:
s <- "This is a big string"

In [65]:
s_sub <- substring(s,5,10)

In [66]:
print(s_sub)

[1] " is a "


In [67]:
s1 <- "Today is New year day"
print(s1)

[1] "Today is New year day"


In [68]:
print(chartr(" ", "-",s1)) # Replace

[1] "Today-is-New-year-day"


In [69]:
character_list <- strsplit(s1, " ") # return List
print(character_list)

[[1]]
[1] "Today" "is"    "New"   "year"  "day"  



In [70]:
word_list <- unlist(character_list) # return Vector
print(word_list)

[1] "Today" "is"    "New"   "year"  "day"  


In [71]:
sort_list <- sort(word_list) # return List
print(sort_list)

[1] "day"   "is"    "New"   "Today" "year" 


In [72]:
sort_list_des <- sort(word_list, decreasing=TRUE) # return List
print(sort_list_des)

[1] "year"  "Today" "New"   "is"    "day"  


# VI. Date

In [73]:
print(date())

[1] "Sat Jan 09 11:06:40 2021"


In [74]:
print(Sys.Date())

[1] "2021-01-09"


In [75]:
d1 <- "16-10-2021"
print(d1)

[1] "16-10-2021"


In [76]:
print(as.Date(d1, format("%d-%m-%Y"))) # Convert to date

[1] "2021-10-16"


In [77]:
print(as.Date("20/10/2021", format("%d/%m/%Y")))

[1] "2021-10-20"


In [78]:
print(format(Sys.Date(), format="%B %d %Y"))

[1] "January 09 2021"


In [79]:
print(format(Sys.Date(), format="%A %B %d %Y"))

[1] "Saturday January 09 2021"


In [80]:
d2 = as.Date(d1, format("%d-%m-%Y"))
print(format(d2, format="%A %B %d %Y"))

[1] "Saturday October 16 2021"


In [81]:
distance <- Sys.Date() - d2
print(distance)

Time difference of -280 days


In [82]:
diff_weeks = difftime(Sys.Date(), as.Date("2021-10-16"), units="weeks")
diff_hours = difftime(Sys.Date(), as.Date("2021-10-16"), units="hours")
diff_minutes = difftime(Sys.Date(), as.Date("2021-10-16"), units="mins")
diff_seconds = difftime(Sys.Date(), as.Date("2021-10-16"), units="secs")
print(diff_weeks)
print(diff_hours)
print(diff_minutes)
print(diff_seconds)

Time difference of -40 weeks
Time difference of -6720 hours
Time difference of -403200 mins
Time difference of -24192000 secs


# Done