In [1]:
print('abc')

[1] "abc"


In [2]:
print(12.5)

[1] 12.5


In [3]:
print(63L)

[1] 63


In [4]:
print(TRUE)

[1] TRUE


In [5]:
print(2+3i)

[1] 2+3i


In [6]:
print(charToRaw('Hello'))

[1] 48 65 6c 6c 6f


In [7]:
v <- 1:10

In [8]:
v

[1]  1  2  3  4  5  6  7  8  9 10

In [9]:
v <- 1.6:5.6
v

[1] 1.6 2.6 3.6 4.6 5.6

In [10]:
v <- 5.8:11.4
v

[1]  5.8  6.8  7.8  8.8  9.8 10.8

In [11]:
v <- seq(2,10,by=0.5)
print(v)

 [1]  2.0  2.5  3.0  3.5  4.0  4.5  5.0  5.5  6.0  6.5  7.0  7.5  8.0  8.5  9.0
[16]  9.5 10.0


In [12]:
colors <- c('red','green','blue','white')
print(colors)

[1] "red"   "green" "blue"  "white"


In [13]:
colors <- c('red','green','blue','black','white','yellow','orange')
print(colors)

[1] "red"    "green"  "blue"   "black"  "white"  "yellow" "orange"


In [14]:
c1 <- colors[c(1,3,5)]
print(c1)

[1] "red"   "blue"  "white"


In [15]:
c2 <- colors[c(-2,-4)]
print(c2)

[1] "red"    "blue"   "white"  "yellow" "orange"


In [16]:
# create two vectors

In [17]:
v1 <- c(5,7,4,8,0,11)
v2 <- c(4,10,2,8,1,2)

In [18]:
length(v1) - length(v2)

[1] 0

In [19]:
add.result <- v1+v2
add.result

[1]  9 17  6 16  1 13

In [20]:
sub.result <- v1-v2
sub.result

[1]  1 -3  2  0 -1  9

In [21]:
multi.result <- v1*v2
multi.result

[1] 20 70  8 64  0 22

In [22]:
div.result <- v2/v1
div.result

[1] 0.8000000 1.4285714 0.5000000 1.0000000       Inf 0.1818182

In [23]:
v1 <- c(5,7,4,8,0,11)
v2 <- c(4,10)

In [24]:
add.result <- v1 + v2
add.result

[1]  9 17  8 18  4 21

In [25]:
v1 <- c(5,7,4,8,0,11)
v2 <- c(4,10,2,8,1)
add.result <- v1 + v2
add.result

Warning message in v1 + v2:
"longer object length is not a multiple of shorter object length"


[1]  9 17  6 16  1 15

In [26]:
length(v1) %% length(v2)==0

[1] FALSE

In [27]:
v <- c(1,2,5,-10,7,-6,9)
v

[1]   1   2   5 -10   7  -6   9

In [28]:
print(sort(v))

[1] -10  -6   1   2   5   7   9


In [29]:
print(sort(v,decreasing=TRUE))

[1]   9   7   5   2   1  -6 -10


In [30]:
colors

[1] "red"    "green"  "blue"   "black"  "white"  "yellow" "orange"

In [31]:
print(sort(colors))

[1] "black"  "blue"   "green"  "orange" "red"    "white"  "yellow"


In [32]:
print(sort(colors), decreasing=TRUE)

[1] "black"  "blue"   "green"  "orange" "red"    "white"  "yellow"


In [33]:
# example(sort)

In [34]:
# Ex1: Vector Friends

In [35]:
friend <- c('Anh','Trang','Chau')
friend

[1] "Anh"   "Trang" "Chau"

In [36]:
friend[c(2,3)]

[1] "Trang" "Chau"

In [37]:
friend[c(length(friend)-1,length(friend)-0)]

[1] "Trang" "Chau"

In [38]:
letters[]

[1] "a" "b" "c" "d" "e" "f" "g" "h" "i" "j" "k" "l" "m" "n" "o" "p" "q" "r" "s"
[20] "t" "u" "v" "w" "x" "y" "z"

In [39]:
gender <- c('Male','Female','Female','Male','Female','Male')

In [40]:
is.factor(gender)

[1] FALSE

In [41]:
factor_gender <- factor(gender)
is.factor(factor_gender)

[1] TRUE

In [42]:
print(factor_gender)

[1] Male   Female Female Male   Female Male  
Levels: Female Male


In [43]:
# # # # # # # # # # # # # # # # # # 

In [44]:
new_order_factor <- factor(factor_gender, levels=c('Male','Female'))
print(new_order_factor)

[1] Male   Female Female Male   Female Male  
Levels: Male Female


In [45]:
colors_factor <- gl(3,5, labels = c('Red','Green','Blue'))
print(colors_factor)

 [1] Red   Red   Red   Red   Red   Green Green Green Green Green Blue  Blue 
[13] Blue  Blue  Blue 
Levels: Red Green Blue


In [46]:
length(colors_factor)

[1] 15

In [47]:
x <- c(1,2,3,3,5,3,2,4,NA,11,22,47,47,11,47,11)

In [48]:
print(paste('Vector: ',toString(x)))

[1] "Vector:  1, 2, 3, 3, 5, 3, 2, 4, NA, 11, 22, 47, 47, 11, 47, 11"


In [49]:
ft <- factor(x)

In [50]:
print(paste('Levels in factor:', levels(ft)))
print(paste('1. Levels in factor:', toString(levels(ft))))
print(paste('2. Number of levels in factor:', nlevels(ft)))

[1] "Levels in factor: 1"  "Levels in factor: 2"  "Levels in factor: 3" 
[4] "Levels in factor: 4"  "Levels in factor: 5"  "Levels in factor: 11"
[7] "Levels in factor: 22" "Levels in factor: 47"
[1] "1. Levels in factor: 1, 2, 3, 4, 5, 11, 22, 47"
[1] "2. Number of levels in factor: 8"


# Matrix

In [51]:
M <- matrix(c(1:12), nrow=4, ncol=3, byrow=TRUE)
print(M)

     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6
[3,]    7    8    9
[4,]   10   11   12


In [52]:
N <- matrix(c(1:12), nrow=4, byrow=FALSE)
print(N)

     [,1] [,2] [,3]
[1,]    1    5    9
[2,]    2    6   10
[3,]    3    7   11
[4,]    4    8   12


In [53]:
N <- matrix(c(1:13), nrow=4, byrow=FALSE)
print(N)

Warning message in matrix(c(1:13), nrow = 4, byrow = FALSE):
"data length [13] is not a sub-multiple or multiple of the number of rows [4]"


     [,1] [,2] [,3] [,4]
[1,]    1    5    9   13
[2,]    2    6   10    1
[3,]    3    7   11    2
[4,]    4    8   12    3


In [54]:
rownames <- c('row1','row2','row3','row4')
colnames <- c('col1','col2','col3')

In [55]:
P <- matrix(c(1:12), nrow=4, byrow=TRUE, dimnames=list(rownames,colnames))
print(P)

     col1 col2 col3
row1    1    2    3
row2    4    5    6
row3    7    8    9
row4   10   11   12


In [56]:
print(P[1,3])

[1] 3


In [57]:
print(P[2,])

col1 col2 col3 
   4    5    6 


In [58]:
print(P[,])

     col1 col2 col3
row1    1    2    3
row2    4    5    6
row3    7    8    9
row4   10   11   12


In [59]:
print(P[,3])

row1 row2 row3 row4 
   3    6    9   12 


In [60]:
class(print(P[,3]))

row1 row2 row3 row4 
   3    6    9   12 


[1] "integer"

In [61]:
typeof(print(P[,3]))

row1 row2 row3 row4 
   3    6    9   12 


[1] "integer"

In [62]:
is.numeric(P[,3])

[1] TRUE

In [63]:
is.matrix(P[,3])

[1] FALSE

In [64]:
is.vector(P[,3])

[1] TRUE

In [65]:
sub = P[1:2,1:2]
print(sub)

     col1 col2
row1    1    2
row2    4    5


In [66]:
sub = P[c(1,4),c(1,3)]
print(sub)

     col1 col3
row1    1    3
row4   10   12


In [67]:
M1 <- matrix(c(1,3,5,7,9,11,13,15), nrow=2, byrow=TRUE)
print(M1)

     [,1] [,2] [,3] [,4]
[1,]    1    3    5    7
[2,]    9   11   13   15


In [68]:
M2 <- matrix(c(0,2,4,6,8,10,12,14), nrow=2, byrow=TRUE)
print(M2)

     [,1] [,2] [,3] [,4]
[1,]    0    2    4    6
[2,]    8   10   12   14


In [71]:
result_add <- M1 + M2 
cat('Result of addition','\n')
print(result_add)

Result of addition 
     [,1] [,2] [,3] [,4]
[1,]    1    5    9   13
[2,]   17   21   25   29


In [72]:
result_sub <- M1 - M2 
cat('Result of subtraction','\n')
print(result_sub)

Result of subtraction 
     [,1] [,2] [,3] [,4]
[1,]    1    1    1    1
[2,]    1    1    1    1


In [73]:
result_mul <- M1 * M2 
cat('Result of multiphication','\n')
print(result_mul)

Result of multiphication 
     [,1] [,2] [,3] [,4]
[1,]    0    6   20   42
[2,]   72  110  156  210


In [74]:
result_div <- M1 / M2 
cat('Result of division','\n')
print(result_div)

Result of division 
      [,1] [,2]     [,3]     [,4]
[1,]   Inf  1.5 1.250000 1.166667
[2,] 1.125  1.1 1.083333 1.071429


In [75]:
m1 <- matrix(c(1:12), ncol=4)
m2 <- matrix(c(1:8),nrow=4)
print(m1)
print(m2)

     [,1] [,2] [,3] [,4]
[1,]    1    4    7   10
[2,]    2    5    8   11
[3,]    3    6    9   12
     [,1] [,2]
[1,]    1    5
[2,]    2    6
[3,]    3    7
[4,]    4    8


In [76]:
m3 <- m1 %*% m2
print(m3)

     [,1] [,2]
[1,]   70  158
[2,]   80  184
[3,]   90  210


In [77]:
vec <- c(1:3)
mat <- matrix(c(1:9), ncol=3)
print(vec)
print(mat)

[1] 1 2 3
     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9


In [78]:
vec_new <- mat %*% vec
print(vec_new)

     [,1]
[1,]   30
[2,]   36
[3,]   42


# 4. Array (row,col,nmatrix)

In [79]:
v1 <- c(1:6)
v2 <- c(7:15)

In [80]:
array1 <- array(v1, dim=c(3,2,2)) # Contain row,col,matrix
print(array1)

, , 1

     [,1] [,2]
[1,]    1    4
[2,]    2    5
[3,]    3    6

, , 2

     [,1] [,2]
[1,]    1    4
[2,]    2    5
[3,]    3    6



In [81]:
array2 <- array(c(v1,v2), dim=c(3,4,2))
print(array2)

, , 1

     [,1] [,2] [,3] [,4]
[1,]    1    4    7   10
[2,]    2    5    8   11
[3,]    3    6    9   12

, , 2

     [,1] [,2] [,3] [,4]
[1,]   13    1    4    7
[2,]   14    2    5    8
[3,]   15    3    6    9



In [89]:
row_names = c('row1','row2','row3')
col_names = c('col1','col2','col3','col4')
mat_names = c('matrix1','matrix2')
array3 <- array(c(v1,v2), dim=c(3,4,2), dimnames=list(row_names,col_names, mat_names))
print(array3)

, , matrix1

     col1 col2 col3 col4
row1    1    4    7   10
row2    2    5    8   11
row3    3    6    9   12

, , matrix2

     col1 col2 col3 col4
row1   13    1    4    7
row2   14    2    5    8
row3   15    3    6    9



In [92]:
array3[2,1,2]

[1] 14

In [94]:
print(array3[,2,1])

row1 row2 row3 
   4    5    6 


In [95]:
print(array3[,2,])

     matrix1 matrix2
row1       4       1
row2       5       2
row3       6       3


In [96]:
print(array3[,,2])

     col1 col2 col3 col4
row1   13    1    4    7
row2   14    2    5    8
row3   15    3    6    9


In [100]:
sub_matrix = array3[c(2,3),c(2,3),2]
print(sub_matrix)

     col2 col3
row2    2    5
row3    3    6


In [102]:
cox <- array3[2:3,2:3,2]
print(cox)

     col2 col3
row2    2    5
row3    3    6


In [103]:
print(apply(array3, c(1),sum))

row1 row2 row3 
  47   55   63 


In [104]:
print(apply(array3, c(2),min))

col1 col2 col3 col4 
   1    1    4    7 


In [105]:
print(apply(array3, c(3),mean))

matrix1 matrix2 
   6.50    7.25 


In [111]:
print(apply(array3, c(1,3),mean))

     matrix1 matrix2
row1     5.5    6.25
row2     6.5    7.25
row3     7.5    8.25


In [108]:
mean(array3)

[1] 6.875

In [112]:
x <- c(1,2,3)
y <- c(4,5,6)
z <- c(7,8,9)

In [114]:
M  <- matrix(c(x,y,z),nrow=3, byrow=TRUE)
print(M)

     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6
[3,]    7    8    9


In [115]:
print(t(M)) # Tranpose

     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9
