In [1]:
list_data <- list('hello','R','12','12.5',c(21,32,11), TRUE)
print(list_data)

[[1]]
[1] "hello"

[[2]]
[1] "R"

[[3]]
[1] "12"

[[4]]
[1] "12.5"

[[5]]
[1] 21 32 11

[[6]]
[1] TRUE



In [3]:
list_1 <- list(c('Red','Green','Yellow'), matrix(c(1:8), nrow=2), list("reen",TRUE,12.5),TRUE)
print(list_1)

[[1]]
[1] "Red"    "Green"  "Yellow"

[[2]]
     [,1] [,2] [,3] [,4]
[1,]    1    3    5    7
[2,]    2    4    6    8

[[3]]
[[3]][[1]]
[1] "reen"

[[3]][[2]]
[1] TRUE

[[3]][[3]]
[1] 12.5


[[4]]
[1] TRUE



In [4]:
names(list_1) <- c('Traffic Light','A_Martix','An Inner List','Pass')

In [5]:
print(list_1)

$`Traffic Light`
[1] "Red"    "Green"  "Yellow"

$A_Martix
     [,1] [,2] [,3] [,4]
[1,]    1    3    5    7
[2,]    2    4    6    8

$`An Inner List`
$`An Inner List`[[1]]
[1] "reen"

$`An Inner List`[[2]]
[1] TRUE

$`An Inner List`[[3]]
[1] 12.5


$Pass
[1] TRUE



In [8]:
list_1$`An Inner List`

[[1]]
[1] "reen"

[[2]]
[1] TRUE

[[3]]
[1] 12.5

In [9]:
list_1[length(list_1)+1] <- 'New element'
print(list_1)

$`Traffic Light`
[1] "Red"    "Green"  "Yellow"

$A_Martix
     [,1] [,2] [,3] [,4]
[1,]    1    3    5    7
[2,]    2    4    6    8

$`An Inner List`
$`An Inner List`[[1]]
[1] "reen"

$`An Inner List`[[2]]
[1] TRUE

$`An Inner List`[[3]]
[1] 12.5


$Pass
[1] TRUE

[[5]]
[1] "New element"



In [10]:
print(list_1[length(list_1)])

[[1]]
[1] "New element"



In [11]:
list_1[length(list_1)] = NULL
print(list_1)

$`Traffic Light`
[1] "Red"    "Green"  "Yellow"

$A_Martix
     [,1] [,2] [,3] [,4]
[1,]    1    3    5    7
[2,]    2    4    6    8

$`An Inner List`
$`An Inner List`[[1]]
[1] "reen"

$`An Inner List`[[2]]
[1] TRUE

$`An Inner List`[[3]]
[1] 12.5


$Pass
[1] TRUE



In [12]:
list_1[2] = NULL
print(list_1)

$`Traffic Light`
[1] "Red"    "Green"  "Yellow"

$`An Inner List`
$`An Inner List`[[1]]
[1] "reen"

$`An Inner List`[[2]]
[1] TRUE

$`An Inner List`[[3]]
[1] 12.5


$Pass
[1] TRUE



In [13]:
list_1[2]

$`An Inner List`
$`An Inner List`[[1]]
[1] "reen"

$`An Inner List`[[2]]
[1] TRUE

$`An Inner List`[[3]]
[1] 12.5

In [14]:
list_1[3] = FALSE
print(list_1)

$`Traffic Light`
[1] "Red"    "Green"  "Yellow"

$`An Inner List`
$`An Inner List`[[1]]
[1] "reen"

$`An Inner List`[[2]]
[1] TRUE

$`An Inner List`[[3]]
[1] 12.5


$Pass
[1] FALSE



In [15]:
list1 <- list(1,TRUE,c('Red','Green','Yellow'))
list2 <- list(TRUE,'hello',12.5)

In [16]:
merged_list <- c(list1,list2)
print(merged_list)

[[1]]
[1] 1

[[2]]
[1] TRUE

[[3]]
[1] "Red"    "Green"  "Yellow"

[[4]]
[1] TRUE

[[5]]
[1] "hello"

[[6]]
[1] 12.5



In [17]:
v1 <- unlist(list1)
print(v1)

[1] "1"      "TRUE"   "Red"    "Green"  "Yellow"


In [18]:
list_diff <- setdiff(list1,list2)
print(list_diff)

[[1]]
[1] 1

[[2]]
[1] "Red"    "Green"  "Yellow"

