# Review Chapter 6 & 7

In [1]:
## Ex1
# Definition of survey_vector
survey_vector <- c("R", "R", "L", "L", "R", "R", "C", "C")

# Encode survey_vector as a factor: survey_factor
survey_vector <- as.factor(survey_vector)
# Print survey_factor
print(survey_vector)
# Print levels of survey_factor
print(levels(survey_vector))
# Print nlevels of survey_factor
print(nlevels(survey_vector))
# How many elements of each factor?
print(length(survey_vector))

[1] R R L L R R C C
Levels: C L R
[1] "C" "L" "R"
[1] 3
[1] 8


In [2]:
## Ex2
# Create my_vector: 1 up to 10
my_vector <- 1:10
# Create my_matrix (3x3): 1 up to 9
my_matrix <- matrix(1:9, nrow=3, ncol=3, byrow=TRUE)
# Create my_factor from sizes
sizes <-c("M","S","L","L","M")

# Construct my_list with the three data structures above
my_list <- list(my_vector, my_matrix, sizes)
# Construct my_super_list with the four data structures above
my_super_list <- list(my_vector, my_matrix, sizes, my_list)
# Display structure of my_super_list (Use str())
str(my_super_list)
# Print my_matrix, sum of my_matrix, sum of even elements in my_matrix
print(my_matrix)
print(sum(my_matrix))
print(rowSums(my_matrix))

List of 4
 $ : int [1:10] 1 2 3 4 5 6 7 8 9 10
 $ : int [1:3, 1:3] 1 4 7 2 5 8 3 6 9
 $ : chr [1:5] "M" "S" "L" "L" ...
 $ :List of 3
  ..$ : int [1:10] 1 2 3 4 5 6 7 8 9 10
  ..$ : int [1:3, 1:3] 1 4 7 2 5 8 3 6 9
  ..$ : chr [1:5] "M" "S" "L" "L" ...
     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6
[3,]    7    8    9
[1] 45
[1]  6 15 24


In [3]:
isPrime.function <- function(n){
    rs <- 1
    if (n<2) {rs <- 0
    } else if (n == 2) {rs <- 1
    } else {
        for (i in 2:(n-1)) {
        if (n%%i ==0) rs <-0
    }}
    return (rs)
}

In [4]:
vector = c()
repeat {
    x <- round(runif(1,1,9),0)
    if (isPrime.function(x) ==  1) {
        vector <- c(vector, x)
    }
    if (length(vector) == 17) break
}
vector <- vector[2:17]
print(vector)

 [1] 7 7 7 3 5 5 7 2 7 5 2 3 7 5 7 3


In [5]:
create.matrix.function <- function(n){
    vector = c()
    repeat {
        x <- round(runif(1,1,9),0)
        if (isPrime.function(x) ==  1) {
            vector <- c(vector, x)
        }
        if (length(vector) == (n*n+1)) break
    }
    vector <- vector[2:17]
    my_matrix <- matrix(vector, nrow=n, ncol=n)
    return (my_matrix)
}


In [6]:
## Ex3: 
# Create my_matrix (4x4): each element is a randomly generated prime number.
my_matrix <- create.matrix.function(4)
# Sum the elements on the main diagonal of the matrix
print(sum(diag(my_matrix)))
# (Note: Build function to create matrix, function to test Prime number, and function to Sum... >> Call fucntion)

[1] 18


In [7]:
my_matrix

[,1] [,2] [,3] [,4]
[1,] 3    7    2    2   
[2,] 2    3    3    2   
[3,] 2    3    7    3   
[4,] 5    2    5    5

In [8]:
## Ex4: 
# Create my_array (4, 4, 2): from 2 matrices created by calling function create_matrix (Ex3)
my_array <- array(c(create.matrix.function(4),create.matrix.function(4)),dim=c(4,4,2))
# Use apply to calculate the min of the rows across all the matrices.
print(apply(my_array, c(2,1),min))
# Use apply to calculate the max of the columns across all the matrices.
print(apply(my_array, c(1,2),max))
# Use apply to calculate the sum of each matrix in my_array
print(apply(my_array,c(1,2), sum))

     [,1] [,2] [,3] [,4]
[1,]    2    2    5    2
[2,]    2    3    2    3
[3,]    2    3    3    5
[4,]    2    2    2    3
     [,1] [,2] [,3] [,4]
[1,]    3    7    5    5
[2,]    2    5    7    7
[3,]    5    7    5    2
[4,]    7    5    7    7
     [,1] [,2] [,3] [,4]
[1,]    5    9    7    7
[2,]    4    8   10    9
[3,]   10    9    8    4
[4,]    9    8   12   10


In [9]:
print(apply(my_array,c(1,2,3),sum))

, , 1

     [,1] [,2] [,3] [,4]
[1,]    3    2    2    2
[2,]    2    3    3    7
[3,]    5    2    5    2
[4,]    2    3    5    7

, , 2

     [,1] [,2] [,3] [,4]
[1,]    2    7    5    5
[2,]    2    5    7    2
[3,]    5    7    3    2
[4,]    7    5    7    3



In [10]:
# done