## List


In [1]:
list_data <- list("hello","R", 12, 25.5, c(21,32,11),TRUE)

In [2]:
print(list_data)

[[1]]
[1] "hello"

[[2]]
[1] "R"

[[3]]
[1] 12

[[4]]
[1] 25.5

[[5]]
[1] 21 32 11

[[6]]
[1] TRUE



In [5]:
# Dat ten cho cac ptu trong list
list_1 <- list(c("Red","Green","Yellow"), matrix(c(1:8), nrow=2), list("green",TRUE, 12.5), TRUE)

In [6]:
names(list_1) <- c("Traffic Light","A_Matrix","A Inner list","Pass")

In [7]:
print(list_1)

$`Traffic Light`
[1] "Red"    "Green"  "Yellow"

$A_Matrix
     [,1] [,2] [,3] [,4]
[1,]    1    3    5    7
[2,]    2    4    6    8

$`A Inner list`
$`A Inner list`[[1]]
[1] "green"

$`A Inner list`[[2]]
[1] TRUE

$`A Inner list`[[3]]
[1] 12.5


$Pass
[1] TRUE



In [11]:
list_1[2]

$A_Matrix
     [,1] [,2] [,3] [,4]
[1,]    1    3    5    7
[2,]    2    4    6    8

In [12]:
list_1$`Traffic Light`

[1] "Red"    "Green"  "Yellow"

In [13]:
list_1$Pass

[1] TRUE

In [14]:
# Them ptu vao list
list_1[length(list_1)+1] = "New element"

In [15]:
list_1

$`Traffic Light`
[1] "Red"    "Green"  "Yellow"

$A_Matrix
     [,1] [,2] [,3] [,4]
[1,]    1    3    5    7
[2,]    2    4    6    8

$`A Inner list`
$`A Inner list`[[1]]
[1] "green"

$`A Inner list`[[2]]
[1] TRUE

$`A Inner list`[[3]]
[1] 12.5


$Pass
[1] TRUE

[[5]]
[1] "New element"

In [18]:
list_1[length(list_1)]

[[1]]
[1] "New element"

In [19]:
# Xoa ptu cuoi cung
list_1[length(list_1)] = NULL

In [20]:
list_1

$`Traffic Light`
[1] "Red"    "Green"  "Yellow"

$A_Matrix
     [,1] [,2] [,3] [,4]
[1,]    1    3    5    7
[2,]    2    4    6    8

$`A Inner list`
$`A Inner list`[[1]]
[1] "green"

$`A Inner list`[[2]]
[1] TRUE

$`A Inner list`[[3]]
[1] 12.5


$Pass
[1] TRUE

In [21]:
list_1[3]= NULL

In [22]:
list_1

$`Traffic Light`
[1] "Red"    "Green"  "Yellow"

$A_Matrix
     [,1] [,2] [,3] [,4]
[1,]    1    3    5    7
[2,]    2    4    6    8

$Pass
[1] TRUE

In [23]:
merge_list <- c(list_data,list_1)

In [24]:
print(merge_list)

[[1]]
[1] "hello"

[[2]]
[1] "R"

[[3]]
[1] 12

[[4]]
[1] 25.5

[[5]]
[1] 21 32 11

[[6]]
[1] TRUE

$`Traffic Light`
[1] "Red"    "Green"  "Yellow"

$A_Matrix
     [,1] [,2] [,3] [,4]
[1,]    1    3    5    7
[2,]    2    4    6    8

$Pass
[1] TRUE



In [25]:
v1 <- unlist(list_data)

In [26]:
v1

[1] "hello" "R"     "12"    "25.5"  "21"    "32"    "11"    "TRUE"